EpistasisLab/Aliro

.travis.yml, docs/source/api.rst
- This PR uses docker for integration tests and unit tests as we did in our Jenkins server.
- Both tests run in parallel in Travis CI
- Deployment of docs is in unit tests' stage because they use the same docker image
=> Refactor Travis CI configuration with adding integration tests and unit tests

docs/guides/developerGuide.md
A small commit to act mostly as a test commit, but I did reformat the Architecture Overview of the guide for easier reading, and added mention of how the terms 'the server' and 'the client' are used in practice.
=> Small changes and typo fixes to developerGuide.md

lab/webapp/src/components/Results/components/Score/index.jsx
Related to issue #257 
The rendering of header icon was computing folds using scoreValueList. Added a condition to avoid this when the list is empty.
=> Avoid calculation of folds when scoreValueList is empty

lab/webapp/package-lock.json, lab/webapp/package.json, lab/webapp/webpack.config.js
'npm run' is now called with --mode option to specify 'development' vs
'production'. 
In development build, webpack sourcemapping is enabled.
View sourcemaps in browser dev tools. Tested successfully with
breakpoint setting in source files in chrome dev tools.
Unity & int. tests passed locally and on Jenkins
Partially resolves #258
=> webapp - add webpack sourcemapping to development mode builds.

docker/lab/files/requirements.txt, docker/machine/files/requirements.txt, lab/webapp/src/components/InvertedCardWithDropdown/index.jsx, lab/webapp/src/components/Results/components/ShapSummaryCurve/index.jsx, lab/webapp/src/components/Results/components/SummaryCurve/index.jsx, lab/webapp/src/components/Results/index.jsx, machine/learn/skl_utils.py, machine/test/learn_tests.py, tests/unit/files/requirements.txt
Adding implementation to visualize SHAP Summary plots for Classification models
- Currently plot images for all classes are created and stored.
- Kernel based explainers are slow, so random sampling of 50 features is performed (updated as 200 was working slower on the recent branch with regression)
- Summary Curves with multiple classes are displayed using a modified form of InvertedCard, named InvertedCardWithDropdown
=> SHAP Summary Plot

lab/webapp/src/components/Results/index.jsx
=> Add 'download script' and 'download model' button to the results pages

.coveragerc, .github/workflows/pennai_tests.yml, .travis.yml, docker/lab/files/requirements.txt, docker/machine/files/requirements.txt
- Fix coveralls in GitHub Action
- Refine workflow
=> Fix coveralls in GitHub Action

ai/recommender/surprise_recommenders.py, docker/lab/Dockerfile, docker/lab/Dockerfile_production, docker/lab/files/requirements.txt, docs/Dockerfile, docs/guides/Scikit_Learn_API_Guide.md, tests/unit/Dockerfile
updates requirements.txt, so it now can handle surprise. 
The surprise fork is updated to track 1.1.1 from the official package, which is 1.1.2 in my fork. 
Also fixes updated function signatures in the surprise recommender.
=> surprise package updates

lab/webapp/dist/App.css, lab/webapp/src/components/FileUpload/index.js, package-lock.json
- add Cancel button (hide file upload area after selecting a file)
- rename Feature Specification to Specification
- rename Dependent Feature to Target
- rename 'Submit' to Upload
- redo Ordinal ranking UI - opens in its own dialog
- Change text-based feature-specification modals to new quasi-modal method, and fix colors
- add auto-selection of target column during init
- add bug fix for text-based specification of categorical features
=> Data upload UI tweaks new

config/unit-test-js-only.env, config/unit-test-py-only.env, docker-compose-unit-test.yml, tests/unit/unit_test_runner.sh
Can now run only python unit tests, only javascript/web unit tests, or
both, using docker-compose and unit-test yml file and new env files.
See notes in `config/unit-test-js-only.env`
After this has been approved, I'll update the developer documentation.
=> Unit testing - add env var-based options for managing which run

docs/source/conf.py, docs/source/index.rst
testing to see if GitHub Pages documentation is updated.
=> Rebranding Sphinx docs conf.py and index.rst

machine/learn/skl_utils.py
update plot learning curve code for the case when wrong hyper-parameters are give to the model
=> update plot learning curve code

lab/webapp/src/components/ScatterPlot/index-working.jsx, lab/webapp/src/components/ScatterPlot/index.jsx
remove comments in the scatterplot components
=> remove comments in the scatterplot component

docker-compose-production.yml, release/deploy_production_release.sh, release/generate_production_release.sh
The updated shell scripts will work with `docker buildx bake` instead of `docker compose` to deploy amd64 and arm64 versions of docker images.
=> Release multiarch

docs/guides/userGuide.md, lab/routes/execapi.js, machine/machine.js, tests/integration/jest/labApi.js, tests/integration/jest/machineApi.test.ts
Fixes issue #597 
Fixes issue with undefined 'length' when calling the /install endpoint with no packages.
Adds new integration tests to code run and install endpoints
=> Fix code executions

aliroed-examples/2_experiment.md
Fix image urls to raw instead of media
=> Aliroed examples image url fix

docs/guides/developerGuide.md
Release procedure is updated to reflect building and publishing multi-architecture docker hub images.
=> Update release procedure instructions

lab/lab.js
Need a check for running experiments before deleting.
If the AI button is enabled and experiments are running, datasets should not be deleted.
=> Add check for running experiments before deleting

lab/lab.js
Checking if the recommender is enabled, and not deleting datasets if it is, since this means that experiments are being launched.
=> Add a check for ai.status before deleting datasets

.env, lab/lab.js, tests/integration/jest/machineApi.test.ts
Updated the datasets `DELETE` endpoint to check the status of the ai and if experiments are running before attempting to delete a dataset.
Added an integration test to validate this works as expected.
=> Delete datasets bug fixes and integration test

raspberrypi/build_rpi/Readme.md, raspberrypi/build_rpi/aliroed-compose.service, raspberrypi/build_rpi/clean.sh
Added aliroed-docker.service and instructions for enabling this service.
Added more instructions to build the aliro-imager.exe
=> Update build_rpi instructions

lab/webapp/src/components/Builder/components/AlgorithmOptions/index.jsx, lab/webapp/src/components/ChatGPT/SideMenu.js, lab/webapp/src/components/Datasets/components/DatasetCard/index.jsx, raspberrypi/intropage/index.html, raspberrypi/intropage/infAndDownloadpage.html, raspberrypi/intropage/int_ml_01.html, raspberrypi/intropage/int_ml_02.html, raspberrypi/intropage/int_ml_03_decision_tree.html
fixed typo and updated the broken download link
=> Update aliroed intropage 
